//数组声明
extern unsigned char const Car[4*2*16]; //车子状态
extern unsigned char const GaoSu[2*2*16]; //高速
extern unsigned char const DiSu[2*2*16]; //低速
extern unsigned char const DuoJiP_A[5*2*16]; //舵机P_A
extern unsigned char const DuoJiP_B[5*2*16]; //舵机P_B
extern unsigned char const DuoJiP_C[5*2*16]; //舵机P_C
extern unsigned char const DuoJi_D[3*2*16]; //舵机D
extern unsigned char const DuoJiFenJieXian[5*2*16]; //舵机分界线
extern unsigned char const DianJi_P[3*2*16]; //电机P
extern unsigned char const DianJi_I[3*2*16]; //电机I
extern unsigned char const YingYanYuZhi[4*2*16]; //鹰眼阈值
extern unsigned char const DaiDingCanShu[4*2*16]; //待定参数
extern unsigned char const TuXiangPianCha[4*2*16]; //图像偏差
extern unsigned char const DuoJiDaJiao[4*2*16]; //舵机打角
extern unsigned char const QianZhan[2*2*16]; //前瞻
extern unsigned char const ShuangCheJuLi[4*2*16]; //双车距离
extern unsigned char const SheDingSuDu[4*2*16]; //设定速度
extern unsigned char const DangQianSuDu[4*2*16]; //当前速度
extern unsigned char const DianJi_PWM[5*2*16]; //电机PWM
extern unsigned char const LuCheng[2*2*16]; //路程
extern unsigned char const DuoJi_P[3*2*16]; //舵机P
extern unsigned char const DianYa[2*2*16]; //电压
extern unsigned char const ShiZi_P[4*2*16]; //十字_P
extern unsigned char const DaiDingXianShi[4*2*16]; //待定显示
extern unsigned char const ShiZi_D[3*2*16]; //十字D
extern unsigned char const WanQuXiShu[4*2*16]; //弯曲系数
extern unsigned char const DuoJiZhongZhi[4*2*16]; //舵机中值
extern unsigned char const DuoJiZuoJiXian[5*2*16]; //舵机左极限
extern unsigned char const DuoJiYouJiXian[5*2*16]; //舵机右极限
extern unsigned char const DuoJi_P_XianFu[5*2*16]; //舵机P限幅
extern unsigned char const TuXiang[2*2*16]; //图像
extern unsigned char const DuoJi[2*2*16]; //舵机
extern unsigned char const MuBiaoSuDu[4*2*16]; //目标速度
extern unsigned char const CanShu1[5*2*16]; //1：参数1
extern unsigned char const CanShu2[5*2*16]; //2：参数2
extern unsigned char const CanShu3[5*2*16]; //3：参数3
extern unsigned char const ChuanTu[4*2*16]; //4：传图
extern unsigned char const QianChe[4*2*16]; //5：前车
extern unsigned char const GuanPingMu[5*2*16]; //6：关屏幕
